# Generated by Django 6.0 on 2025-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='s_language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_vdate',
            field=models.DateTimeField(auto_now=True, verbose_name='방문일시'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='s_contents',
            field=models.TextField(null=True, verbose_name='안전 자료 내용'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='s_created_at',
            field=models.DateField(null=True, verbose_name='안전 자료 작성일'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='s_image_url',
            field=models.URLField(max_length=2000, verbose_name='안전 자료 이미지 url'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='s_link',
            field=models.URLField(max_length=2000, verbose_name='안전 상세페이지 링크'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='s_type',
            field=models.CharField(max_length=30, verbose_name='안전 자료 형태'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='s_video_url',
            field=models.URLField(max_length=2000, null=True, verbose_name='안전 자료 동영상 url'),
        ),
        migrations.AlterField(
            model_name='safe',
            name='tags',
            field=models.ManyToManyField(related_name='materials', through='safe.SafeTag', to='safe.tag', verbose_name='태그'),
        ),
        migrations.AddConstraint(
            model_name='safetag',
            constraint=models.UniqueConstraint(fields=('safe', 'tag'), name='unique_safe_tag'),
        ),
    ]
