# Generated by Django 5.2.8 on 2025-12-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_m_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='i_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='사고위치 위도'),
        ),
        migrations.AddField(
            model_name='individual',
            name='i_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='사고위치 경도'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_sex',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=6, verbose_name='성'),
        ),
    ]
