# Generated by Django 5.2.8 on 2025-12-16 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_individual_i_lat_individual_i_lng_alter_member_m_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='i_title',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='산재제목은 한글, 영어, 숫자만 입력 가능합니다.', regex='^[가-힣a-zA-Z0-9]+$')], verbose_name='산재제목'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_name',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='이름은 한글만 입력 가능하며 최대 10글자까지 가능합니다.', regex='^[가-힣]{1,10}$')], verbose_name='이름'),
        ),
    ]
