# Generated by Django 5.2.8 on 2025-12-17 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_individual_i_title_alter_member_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='이름은 한글, 영어, 숫자만 입력 가능하며 1~20글자까지 가능합니다.', regex='^[가-힣a-zA-Z0-9]{1,20}$')], verbose_name='이름'),
        ),
    ]
